### ISSUE TITLE
Help with running mutation in Chapter 2

### ISSUE THREAD

**Issue by SeanPCarter** [PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition#5] opened 2022-09-28 16:19 UTC
Does anyone know how to make this work in Postman from pg 67/68 Chapter 2?

{
"operationName" : null,
"query": "mutation addPost($post : PostInput!,
$user: UserInput!) {
addPost(post : $post, user: $user) {
  id
  text
  user {
     username
     avatar
   }
 }
}",
"variables": {
  "post": {
     "test": "You just added a post."
  },
"user": {
  "avatar": "/uploads/avatar3.png",
  "username": "Fake User"
   }
  }
}

**Comment by sebastiangrebe** [comment] 2022-10-15 12:48
@SeanPCarter You should be able to send this as a POST request against the GraphQL endpoint.
Can you clarify what the problem is?

**Comment by vatoer** [comment] 2022-12-05 09:35
> 

@SeanPCarter try to write inline the query 

```
"query": "mutation addPost($post: PostInput!, $user: UserInput!) { addPost(post: $post, user: $user) {id  text user { username avatar } } }",
```

some API clients can't handle multi row json

**Comment by SeanPCarter** [comment] 2022-12-05 18:07
Thanks,

I'll give that a try and give an update on how I did

thanks
spc
________________________________

**Comment by SeanPCarter** [comment] 2022-12-06 03:44
@vatoer 

I think that was the problem. This returned an error

{
    "operationName": null, 
    "query": "{
        posts {
            id 
            text
            }
       }"
}

But this returned a valid response:

{
    "operationName": null, "query": "{posts {id text}}"
}

Thanks for all your help

**Comment by sebastiangrebe** [comment] 2022-12-06 16:36
Awesome, closing this then!

**Closed as completed by sebastiangrebe** 2022-12-06 16:36 UTC
